.\"
.\" Copyright © 2016 Keith Packard <keithp@keithp.com>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License along
.\" with this program; if not, write to the Free Software Foundation, Inc.,
.\" 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
.\"
.\"
.TH CHAOSREAD 1 "chaosread" ""
.SH NAME
chaosread \- read raw noise source from chaoskey
.SH SYNOPSIS
.B "chaosread"
.SH DESCRIPTION
.I chaosread
reads ADC values from the noise source on the attached ChaosKey device.
.SH OPTIONS
.TP
\-s serial | --serial serial
This selects a ChaosKey by serial number instead of using the first
one found.
.TP
\-l length | --length length
Set the amount of data to read. Suffixes 'k', 'M' and 'G' are
supported. The default is 1k.
.TP
\-i | --infinite
Keep reading forever (or until the process is killed).
.TP
\-b | --bytes
Read 16-bits little endian values and write out one byte per sample
from bits 1-8 of the sample (zero-based, so shift right by one).
.SH USAGE
.I chaosread
reads noise data.
.SH AUTHOR
Keith Packard
